### ISSUE TITLE
Mismatch IsIsomorphicCubefreeGroups (manual) vs IsIsomorphismCubefreeGroups (code)

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/cubefree#3]
The documentation mentions a function `IsIsomorphicCubefreeGroups` which does
not exist. In the coder, there is a function `IsIsomorphismCubefreeGroups`.
Presumably they are the same, and the names should be aligned.

@heikodietrich I can take care of this right away, if you simply let me know
which name you prefer (I'd say `IsIsomorphicCubefreeGroups` is better, though strange;
how about `AreIsomorphicCubefreeGroups` ?)

**Comment by heikodietrich** [comment]
Thank you so much! If you could change that before your wrap up, that would be great. I think I would vote for "IsIsomorphicCubefreeGroups" (motivated by Magma's "IsIsomorphicPGroup"); while "AreIsom..." seem grammatically more correct, it also sounds a bit strange...
Thanks!

**Comment by fingolfin** [comment]
`IsIsomorphicCubefreeGroups` it is :-)
